#
# This file is part of ***  M y C o R e  ***
# See http://www.mycore.de/ for details.
#
# MyCoRe is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# MyCoRe is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with MyCoRe.  If not, see <http://www.gnu.org/licenses/>.
#

# $Revision$ : $Date$

# name of project - ZMO
MCR.NameOfProject=zmo
MIR.projectid.default=zmo


# supported languages
MCR.Metadata.Languages=de,en


# solr
#MCR.Solr.Core.main.ServerURL=%MCR.Solr.ServerURL%
MCR.Solr.NestedDocuments=true
MCR.Solr.Proxy.WhiteList=%MCR.Solr.Proxy.WhiteList%


# Customization of XEditor forms
MIR.EditorForms.CustomIncludes=%MIR.EditorForms.CustomIncludes%,xslStyle:editor/mir2xeditor:webapp:editor/editor-customization.xed
###############################################################################
#                                                                             #
# Generic mail configuration for MCRMailer                                    #
#                                                                             #
###############################################################################

# The server for outgoing mails
MCR.Mail.Server=mailer.gbv.de

# The mail protocol
MCR.Mail.Protocol=smtp

# The debug option
MCR.Mail.Debug=false

# Encoding for the mail
MCR.Mail.Encoding=UTF-8

# Number of send tries
MCR.Mail.NumTries=3

# Editor Mail adresses for Messages add1@serv1,add2@serv2,...
MCR.Mail.Address=
MCR.Mail.Sender=%MCR.mir-module.MailSender%


##############################################################################
#                                                                            #
# DOI configuration                                                          #
#                                                                            #
##############################################################################

# activate in test or production
MCR.PI.Service.Datacite=org.mycore.pi.doi.MCRDOIService

# overwrite for test fabrica usage https://doi.test.datacite.org/repositories/
MCR.DOI.Prefix=10.82566
MCR.DOI.Resolver.MasterURL=https://handle.stage.datacite.org/
MCR.PI.Service.Datacite.UseTestServer=true
MCR.PI.Service.Datacite.RegisterBaseURL=https://reposis-test.gbv.de/zmo/


##############################################################################
#                                                                            #
# Dev Env Settings                                                           #
#                                                                            #
##############################################################################

MCR.LayoutService.LastModifiedCheckPeriod=0
MCR.UseXSLTemplateCache=false
MCR.SASS.DeveloperMode=true
MCR.Developer.Resource.Override=/mcr/home/resources,/mcr/home/save/webpages/mir-layout

MCR.EventHandler.MCRDerivate.080.Class=
MCR.EventHandler.MCRPath.100.Class=

# Do i18n in a separate step to translate webpages and labels
MCR.LayoutTransformerFactory.Default.Stylesheets=%MCR.LayoutTransformerFactory.Default.Stylesheets%,xsl/i18n-transformation-step.xsl,xsl/xhtml2html.xsl:

##############################################################################
# MIR ePuSta                                                                    #
##############################################################################
# show ePuSta statistics in metadata view ('show', 'hide')
MIR.ePuSta=show

# URL of the graphprovider
MIR.ePuSta.GraphProviderURL=https://repositorium.zmo.de/graphprovider/
MIR.ePuSta.Prefix=
