# The following properties are required for zmo (productive) deployment.
# For productive deployment, all properties must be configured or enabled.
# Only relevant properties should be listed here; otherwise, they should be deleted.
# Unless otherwise specified, empty properties are relevant and must be configured.
# Temporary disabled properties require further configuration or other dependencies.

##############################################################################
# Basic                                                                      #
##############################################################################
# Configure base url, e.g. http://domain:port, without '/'. Temporary disabled to use default.
#MCR.baseurl=
# Requires MCR.baseurl, therefore temporary disabled.
#MIR.CanonicalBaseURL=%MCR.baseurl%/
MCR.NameOfProject=zmo
MIR.projectid.default=zmo
MIR.testEnvironment=false

##############################################################################
# Access Control                                                             #
##############################################################################
# Access keys are not relevant and must therefore be deactivated as follows.
MCR.ACL.AccessKey.Strategy.AllowedObjectTypes=

##############################################################################
# Email                                                                      #
##############################################################################
MCR.Mail.Server=
# General sender mail address, e.g. mail@domain.
MCR.Mail.Sender=

# Mail for events including self registration, e.g. <name> mail@domain.
MCR.mir-module.EditorMail=
# Sender email for events, e.g. <name> mail@domain.
MCR.mir-module.MailSender=

##############################################################################
# DOI                                                                        #
##############################################################################
MCR.DOI.Prefix=10.82566
MCR.PI.Service.Datacite.HostingInstitution=

# Configuration is required, therefore service temporary disabled.
#MCR.PI.Service.Datacite=org.mycore.pi.doi.MCRDOIService
MCR.PI.Service.Datacite.RegisterBaseURL=%MCR.baseurl%
MCR.PI.Service.Datacite.Username=
MCR.PI.Service.Datacite.Password=

##############################################################################
# OAI Data Provider                                                          #
##############################################################################
MCR.OAIDataProvider.OAI2.RepositoryName=Institutionelles Repositorium ZMO
MCR.OAIDataProvider.OAI2.RepositoryIdentifier=%MCR.baseurl%/
MCR.OAIDataProvider.OAI2.AdminEmail=
MCR.OAIDataProvider.OAI2.RecordSampleID=%MIR.projectid.default%_mods_00000321
MCR.OAIDataProvider.OAI2.DescriptionURI.EPrints=webapp:oai/oai-eprints.xml
MCR.OAIDataProvider.OAI2.DescriptionURI.Rights=webapp:oai/oai-rights.xml

##############################################################################
# ePuSta                                                                     #
##############################################################################
# ePuSta endpoint is required, therefore temporarily disabled.
#MIR.ePuSta=show
MIR.ePuSta.providerURL=

##############################################################################
# Editor                                                                     #
##############################################################################
MIR.EditorForms.CustomIncludes=%MIR.EditorForms.CustomIncludes%,xslStyle:editor/mir2xeditor:webapp:editor/editor-customization.xed,xslStyle:editor/mir2xeditor:webapp:editor/zmo-editor-includes.xed

##############################################################################
# Frontend                                                                   #
##############################################################################
MIR.CustomLayout.JS=zmo.js
# Do i18n in a separate step to translate webpages and labels.
MCR.LayoutTransformerFactory.Default.Stylesheets=%MCR.LayoutTransformerFactory.Default.Stylesheets%,xsl/i18n-transformation-step.xsl,xsl/xhtml2html.xsl
# Additional style sheets.
MCR.URIResolver.xslIncludes.MyCoReWebPage=%MCR.URIResolver.xslIncludes.MyCoReWebPage%,zmo-templates.xsl

##############################################################################
# Solr                                                                       #
##############################################################################
MCR.Solr.NestedDocuments=true
MCR.Solr.Proxy.WhiteList=%MCR.Solr.Proxy.WhiteList%
