# The following properties are required for zmo (productive) deployment.
# For productive deployment, all properties must be configured or enabled.
# Only relevant properties should be listed here; otherwise, they should be deleted.
# Unless otherwise specified, empty properties are relevant and must be configured.
# Temporary disabled properties require further configuration or other dependencies.

##############################################################################
# Basic                                                                      #
##############################################################################
# Configure base url, e.g. http://domain:port, without '/'. Temporary disabled to use default.
#MCR.baseurl=
# Requires MCR.baseurl, therefore temporary disabled.
#MIR.CanonicalBaseURL=%MCR.baseurl%/
MCR.NameOfProject=zmo
MIR.projectid.default=zmo
MIR.testEnvironment=false

##############################################################################
# Access Control                                                             #
##############################################################################
# Access keys are not relevant and must therefore be deactivated as follows.
MCR.ACL.AccessKey.Strategy.AllowedObjectTypes=

MIR.Access.Strategy.Classifications=mir_access,state

# Grant author all permissions while document is in state submitted.
MCR.Access.Strategy.CreatorPermissions=read,writedb,view-derivate,deletedb

##############################################################################
# Email                                                                      #
##############################################################################
MCR.Mail.Server=
# General sender mail address, e.g. mail@domain.
MCR.Mail.Sender=

# Mail for events including self registration, e.g. <name> mail@domain.
MCR.mir-module.EditorMail=
# Sender email for events, e.g. <name> mail@domain.
MCR.mir-module.MailSender=

##############################################################################
# DOI                                                                        #
##############################################################################
MCR.DOI.Prefix=10.58144
MCR.PI.Service.Datacite.HostingInstitution=Leibniz-Zentrum Moderner Orient

# Configuration is required, therefore service temporary disabled.
#MCR.PI.Service.Datacite=org.mycore.pi.doi.MCRDOIService
MCR.PI.Service.Datacite.MetadataService=MODSDOI
MCR.PI.Service.Datacite.RegisterBaseURL=%MCR.baseurl%
MCR.PI.Service.Datacite.Username=
MCR.PI.Service.Datacite.Password=
MCR.PI.Service.Datacite.Transformer=datacite
MCR.PI.Service.Datacite.RegistrationPredicate=org.mycore.pi.condition.MCRPIPublishedPredicate
MCR.PI.Service.Datacite.RegisterURLContext=receive/$ID
MCR.PI.Service.Datacite.Generator=zmoDOI

MCR.PI.Generator.zmoDOI=org.mycore.pi.MCRGenericPIGenerator
MCR.PI.Generator.zmoDOI.GeneralPattern=%MCR.DOI.Prefix%/$ObjectDate-$Count
MCR.PI.Generator.zmoDOI.DateFormat=yyyyMMdd
MCR.PI.Generator.zmoDOI.CountPrecision=3
MCR.PI.Generator.zmoDOI.Type=doi

MCR.PI.MetadataService.MODSDOI=org.mycore.mods.identifier.MCRMODSDOIMetadataService
MCR.PI.MetadataService.MODSDOI.Prefix=%MCR.DOI.Prefix%

##############################################################################
# URN configuration                                                          #
##############################################################################
MCR.URN.Resolver.MasterURL=https://nbn-resolving.org/
MCR.PI.MetadataService.MODSURN.Prefix=urn:nbn:de:0307
MCR.PI.Generator.TypeYearCountURN.GeneralPattern=urn:nbn:de:0307-$ObjectDate-$Count-
MCR.PI.Generator.TypeYearCountURN.DateFormat=yyyyMMdd
MCR.PI.Generator.TypeYearCountURN.CountPrecision=3

##############################################################################
# OAI Data Provider                                                          #
##############################################################################
MCR.OAIDataProvider.OAI2.RepositoryName=Institutionelles Repositorium ZMO
MCR.OAIDataProvider.OAI2.RepositoryIdentifier=%MCR.baseurl%/
MCR.OAIDataProvider.OAI2.AdminEmail=
MCR.OAIDataProvider.OAI2.RecordSampleID=%MIR.projectid.default%_mods_00000321
MCR.OAIDataProvider.OAI2.DescriptionURI.EPrints=webapp:oai/oai-eprints.xml
MCR.OAIDataProvider.OAI2.DescriptionURI.Rights=webapp:oai/oai-rights.xml
MCR.OAIDataProvider.OAI2.DeletedRecord=transient

# If name, place and the address of the repository owner.
MCR.OAIDataProvider.RepositoryPublisherName=Institutionelles Repositorium ZMO \r\nLeibniz-Zentrum Moderner Orient
MCR.OAIDataProvider.RepositoryPublisherPlace=Berlin
MCR.OAIDataProvider.RepositoryPublisherAddress=Sch\u00FCtzenstra\u00DFe 18

MIR.xMetaDissPlus.diniPublType.classificationId=diniPublType2022
MIR.dc.diniPublType.classificationId=diniPublType2022
MIR.dc.ignoredClassificationIds=diniPublType

# Metadata formats
MCR.OAIDataProvider.MetadataFormat.xMetaDissPlus.Schema=http://files.dnb.de/standards/xmetadissplus/xmetadissplus.xsd
MCR.OAIDataProvider.MetadataFormat.xMetaDissPlus.Namespace=http://www.d-nb.de/standards/xmetadissplus/
MCR.OAIDataProvider.OAI2.MetadataFormats=oai_dc,mods,epicur,xMetaDissPlus

# Set specifications
MCR.OAIDataProvider.OAI2.Sets.doc-type.URI=xslStyle:classification2sets:classification:metadata:2:children:diniPublType2022
MCR.OAIDataProvider.OAI2.Sets.doc-type.Classification=diniPublType2022
MCR.OAIDataProvider.OAI2.MapSetToQuery.xmetadissplus=derCount:[1 TO *] AND NOT(mods.type:video OR mods.type:research_data OR mods.type:journal OR mods.type:series) AND state:published AND objectType:mods
MCR.OAIDataProvider.OAI2.Sets.xmetadissplus.URI=webapp:oai/set_xmetadissplus.xml
MCR.OAIDataProvider.OAI2.Sets=doc-type,open_access,openaire,driver,ec_fundedresources,GENRE,ddc,xmetadissplus

# Enable the URN set configured by reposis_common.
MCR.OAIDataProvider.OAI2.Sets=%MCR.OAIDataProvider.OAI2.Sets%,urn
MCR.OAIDataProvider.OAI2.Sets.urn.Query=mods.identifier:urn* AND mods.identifier:*0307-*

# friendly OAI interfaces
MCR.OAIDataProvider.OAI2.Friends.LeibnitzOpen=https://leibnizopen.de/oaip/oai
MCR.OAIDataProvider.OAI2.Friends.BaseSearch=http://oai.base-search.net/oai
MCR.OAIDataProvider.OAI2.Friends.DDB=https://oai.deutsche-digitale-bibliothek.de

##############################################################################
# ePuSta                                                                     #
##############################################################################
# ePuSta endpoint is required, therefore temporarily disabled.
#MIR.ePuSta=show
MIR.ePuSta.providerURL=

##############################################################################
# Editor                                                                     #
##############################################################################
MIR.EditorForms.CustomIncludes=%MIR.EditorForms.CustomIncludes%,xslStyle:editor/mir2xeditor:webapp:editor/editor-customization.xed,xslStyle:editor/mir2xeditor:webapp:editor/zmo-editor-includes.xed
# Exclude genres from licence validation.
MIR.Editor.Validate.Genre.Licence=journal newspaper series lecture archivebox

##############################################################################
# Frontend                                                                   #
##############################################################################
MIR.CustomLayout.JS=zmo.js
# Do i18n in a separate step to translate webpages and labels.
MCR.LayoutTransformerFactory.Default.Stylesheets=%MCR.LayoutTransformerFactory.Default.Stylesheets%,xsl/i18n-transformation-step.xsl,xsl/xhtml2html.xsl
# Additional style sheets.
MCR.URIResolver.xslIncludes.MyCoReWebPage=%MCR.URIResolver.xslIncludes.MyCoReWebPage%,zmo-templates.xsl

##############################################################################
# Solr                                                                       #
##############################################################################
MCR.Solr.NestedDocuments=true
MCR.Solr.Proxy.WhiteList=%MCR.Solr.Proxy.WhiteList%
MIR.Rules.Solr.Protected.RequestHandler=find,select

##############################################################################
# Citation                                                                   #
##############################################################################
# A comma separated list of styles, look here http://crosscite.org/citeproc/
MIR.citationStyles=din-1505-2,apa,elsevier-harvard,springer-basic-author-date
MIR.defaultCitationStyle=din-1505-2

# Export styles
MCR.Export.CSL.Styles=%MIR.citationStyles%

##############################################################################
# Enrichment                                                                 #
##############################################################################
MCR.MODS.EnrichmentResolver.DataSources.import=(Scopus PubMed IEEE CrossRef DataCite) OADOI GBV ZDB JOP
